### PR TITLE
Upgrade to get-stream/stream ^3.0

### PR DESCRIPTION
**Pull request by qdequippe**
- Upgrade to get-stream/stream ^3.0
- `composer.lock` added to git to work on same dependencies across contributors (and CI)
- Tests fixed due to upgrade

### CODE REVIEW

**Comment by tbarbugli** [comment]
good one!

**Comment by qdequippe** [comment]
@tbarbugli so quick! thank you! could you make a new release?

**Comment by tbarbugli** [comment]
I was too quick indeed, looks like the new lockfile breaks PHP compat

**Comment by tbarbugli** [comment]
(see Travis build)

**Comment by qdequippe** [comment]
@tbarbugli arf sorry I will check this

**Comment by qdequippe** [comment]
@tbarbugli what about to drop support of php 5.6? (5.6 is in EOL)

**Comment by qdequippe** [comment]
@tbarbugli what about removing composer.lock?

**Pull request merged**
